version: "3"
services:

  web:
    image: guicarvalho/curso-flask:dev
    build:
      context: .
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/project
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASS=root
      - POSTGRES_DB=coffee_shop
