"""empty message

Revision ID: 610beadb8b9b
Revises: 94f1c3fac427
Create Date: 2018-10-15 05:42:36.471925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '610beadb8b9b'
down_revision = '94f1c3fac427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_uuid', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['role_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_uuid')
    # ### end Alembic commands ###
