"""empty message

Revision ID: ada00a6eaa3f
Revises: 610beadb8b9b
Create Date: 2018-10-17 23:52:21.126068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ada00a6eaa3f'
down_revision = '610beadb8b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('product_sale',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('product_uuid', postgresql.UUID(), nullable=False),
    sa.Column('sale_uuid', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_uuid'], ['product.uuid'], ),
    sa.ForeignKeyConstraint(['sale_uuid'], ['sale.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_sale')
    op.drop_table('sale')
    # ### end Alembic commands ###
